### ISSUE TITLE
Upload limit for uploading media

### ISSUE THREAD

**Issue by alvaroov** [positiondev/mxlinche#14]
There is currently an upload limit for media of 25mb. 

Is there a way to increase this?

http://www.wpbeginner.com/wp-tutorials/how-to-increase-the-maximum-file-upload-size-in-wordpress/

**Comment by emhoracek** [comment]
Yes! There definitely is.

I'm going to increase it to 100MB for now, let me know if that's not big enough. 

A tricky thing with uploads is that an attacker could conceivably use large uploads to take down your site -- they would repeatedly attempt to upload some huge file until the server choked. So it's best not to allow arbitrarily large files. Videos and very long audio files that should be hosted on YouTube or another service and embedded in your posts, instead of uploaded to WordPress.

**Comment by emhoracek** [comment]
Upload limit is increased. @alvaroov could you try uploading again and comment here to let me know it's working now?

**Comment by emhoracek** [comment]
@alvaroov I think it's fixed! https://grafnyc-staging.positiondevapp.com/app/uploads/2017/01/snackingraccoon.gif <- a 70MB gif (do not open on your cell plan lol)

**Comment by alvaroov** [comment]
Great seems like this is solved now!
